server:
  port: 9090

spring:
  application:
    name: jwt-authentification
  datasource:
    url: jdbc:mysql://localhost:3306/authentification_project
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
